package geoqlparser

type typ int

const (
	intTyp typ = iota + 1
	floatTyp
	stringTyp
	stringArrayTyp
	durationTyp
	radiusTyp
	booleanTyp
	timeTyp
)

var opList = map[typ][]Token{
	intTyp:      []Token{GEQ, LEQ, NEQ, GTR, LSS},
	floatTyp:    []Token{GEQ, LEQ, NEQ, GTR, LSS},
	stringTyp:   []Token{},
	durationTyp: []Token{},
	radiusTyp:   []Token{},
	booleanTyp:  []Token{},
	timeTyp:     []Token{},
}

var kwdTypList = map[Token]typ{
	NMEA_AAM_STATUS_ARRIVAL_CIRCLE_ENTERED: stringTyp,
	NMEA_AAM_STATUS_PERPENDICULAR_PASSED:   stringTyp,
	NMEA_AAM_ARRIVAL_CIRCLE_RADIUS:         floatTyp,
	NMEA_AAM_ARRIVAL_CIRCLE_UNIT:           stringTyp,
	NMEA_AAM_DESTINATION_WAYPOINT_ID:       stringTyp,
	NMEA_ALA_TIME:                          timeTyp,
	NMEA_ALA_SYSTEM_INDICATOR:              stringTyp,
	NMEA_ALA_SUB_SYSTEM_INDICATOR:          stringTyp,
	NMEA_ALA_INSTANCE_NUMBER:               intTyp,
	NMEA_ALA_TYPE:                          intTyp,
	NMEA_ALA_CONDITION:                     stringTyp,
	NMEA_ALA_ALARM_ACK_STATE:               stringTyp,
	NMEA_ALA_MESSAGE:                       stringTyp,
	NMEA_APB_STATUS_GENERAL_WARNING:        stringTyp,
	NMEA_APB_STATUS_LOCK_WARNING:           stringTyp,
	NMEA_APB_CROSS_TRACK_ERROR_MAGNITUDE:   floatTyp,
	NMEA_APB_DIRECTION_TO_STEER:            stringTyp,
	NMEA_APB_CROSS_TRACK_UNITS:             stringTyp,
	NMEA_APB_STATUS_ARRIVAL_CIRCLE_ENTERED: stringTyp,
	NMEA_APB_STATUS_PERPENDICULAR_PASSED:   stringTyp,
	NMEA_APB_BEARING_ORIGIN_TO_DEST:        floatTyp,
	NMEA_APB_BEARING_ORIGIN_DEST_TYPE:      stringTyp,
	NMEA_APB_DESTINATION_WAYPOINT_ID:       stringTyp,
	NMEA_APB_BEARING_PRESENT_TO_DEST:       floatTyp,
	NMEA_APB_BEARING_PRESENT_TO_DEST_TYPE:  stringTyp,
	NMEA_APB_HEADING:                       floatTyp,
	NMEA_APB_HEADING_TYPE:                  stringTyp,
	NMEA_APB_FFA_MODE:                      stringTyp,
	NMEA_BEC_TIME:                          timeTyp,
	NMEA_BEC_LATITUDE:                      floatTyp,
	NMEA_BEC_LONGITUDE:                     floatTyp,
	NMEA_BEC_BEARING_TRUE:                  floatTyp,
	NMEA_BEC_BEARING_TRUE_VALID:            booleanTyp,
	NMEA_BEC_BEARING_MAGNETIC:              floatTyp,
	NMEA_BEC_BEARING_MAGNETIC_VALID:        booleanTyp,
	NMEA_BEC_DISTANCE_NAUTICAL_MILES:       floatTyp,
	NMEA_BEC_DISTANCE_NAUTICAL_MILES_VALID: booleanTyp,
	NMEA_BEC_DESTINATION_WAYPOINT_ID:       stringTyp,
	NMEA_BOD_BEARING_TRUE:                  floatTyp,
	NMEA_BOD_BEARING_TRUE_TYPE:             stringTyp,
	NMEA_BOD_BEARING_MAGNETIC:              floatTyp,
	NMEA_BOD_BEARING_MAGNETIC_TYPE:         stringTyp,
	NMEA_BOD_DESTINATION_WAYPOINT_ID:       stringTyp,
	NMEA_BOD_ORIGIN_WAYPOINT_ID:            stringTyp,
	NMEA_BWC_TIME:                          timeTyp,
	NMEA_BWC_LATITUDE:                      floatTyp,
	NMEA_BWC_LONGITUDE:                     floatTyp,
	NMEA_BWC_BEARING_TRUE:                  floatTyp,
	NMEA_BWC_BEARING_TRUE_TYPE:             stringTyp,
	NMEA_BWC_BEARING_MAGNETIC:              floatTyp,
	NMEA_BWC_BEARING_MAGNETIC_TYPE:         stringTyp,
	NMEA_BWC_DISTANCE_NAUTICAL_MILES:       floatTyp,
	NMEA_BWC_DISTANCE_NAUTICAL_MILES_UNIT:  stringTyp,
	NMEA_BWR_TIME:                          timeTyp,
	NMEA_BWR_LATITUDE:                      floatTyp,
	NMEA_BWR_LONGITUDE:                     floatTyp,
	NMEA_BWR_BEARING_TRUE:                  floatTyp,
	NMEA_BWR_BEARING_TRUE_TYPE:             stringTyp,
	NMEA_BWR_BEARING_MAGNETIC:              floatTyp,
	NMEA_BWR_BEARING_MAGNETIC_TYPE:         stringTyp,
	NMEA_BWR_DISTANCE_NAUTICAL_MILES:       floatTyp,
	NMEA_BWR_DESTINATION_WAYPOINT_ID:       stringTyp,
	NMEA_BWR_FFA_MODE:                      stringTyp,
	NMEA_BWW_BEARING_TRUE:                  floatTyp,
	NMEA_BWW_BEARING_TRUE_TYPE:             stringTyp,
	NMEA_BWW_BEARING_MAGNETIC:              floatTyp,
	NMEA_BWW_BEARING_MAGNETIC_TYPE:         stringTyp,
	NMEA_BWW_DESTINATION_WAYPOINT_ID:       stringTyp,
	NMEA_BWW_ORIGINAL_WAYPOINT_ID:          stringTyp,
	NMEA_DBK_DEPTH_FEET:                    floatTyp,
	NMEA_DBK_DEPTH_FEET_UNIT:               stringTyp,
	NMEA_DBK_DEPTH_METERS:                  floatTyp,
	NMEA_DBK_DEPTH_METERS_UNIT:             stringTyp,
	NMEA_DBK_DEPTH_FATHOMS:                 floatTyp,
	NMEA_DBK_DEPTH_FATHOMS_UNIT:            stringTyp,
	NMEA_DBS_DEPTH_FEET:                    floatTyp,
	NMEA_DBS_DEPTH_FEET_UNIT:               stringTyp,
	NMEA_DBS_DEPTH_METERS:                  floatTyp,
	NMEA_DBS_DEPTH_METERS_UNIT:             stringTyp,
	NMEA_DBS_DEPTH_FATHOMS:                 floatTyp,
	NMEA_DBS_DEPTH_FATHOMS_UNIT:            stringTyp,
	NMEA_DBT_DEPTH_FEET:                    floatTyp,
	NMEA_DBT_DEPTH_METERS:                  floatTyp,
	NMEA_DBT_DEPTH_FATHOMS:                 floatTyp,
	NMEA_DOR_TYPE:                          stringTyp,
	NMEA_DOR_TIME:                          timeTyp,
	NMEA_DOR_SYSTEM_INDICATOR:              stringTyp,
	NMEA_DOR_DIVISION_INDICATOR1:           stringTyp,
	NMEA_DOR_DIVISION_INDICATOR2:           intTyp,
	NMEA_DOR_DOOR_NUMBER_OR_COUNT:          intTyp,
	NMEA_DOR_DOOR_STATUS:                   stringTyp,
	NMEA_DOR_SWITCH_SETTING:                stringTyp,
	NMEA_DOR_MESSAGE:                       stringTyp,
	NMEA_DPT_DEPTH:                         floatTyp,
	NMEA_DPT_OFFSET:                        floatTyp,
	NMEA_DPT_RANGE_SCALE:                   floatTyp,
	NMEA_DSC_FORMAT_SPECIFIER:              stringTyp,
	NMEA_DSC_ADDRESS:                       stringTyp,
	NMEA_DSC_CATEGORY:                      stringTyp,
	NMEA_DSC_DISTRESS_CAUSE_OR_TELE_CMD1:   stringTyp,
	NMEA_DSC_CMD_TYPE_OR_TELE_CMD2:         stringTyp,
	NMEA_DSC_POSITION_OR_CANAL:             stringTyp,
	NMEA_DSC_TIMER_OR_TELE_NUMBER:          stringTyp,
	NMEA_DSC_MMSI:                          stringTyp,
	NMEA_DSC_DISTREES_CAUSE:                stringTyp,
	NMEA_DSC_ACK_LEDGEMENT:                 stringTyp,
	NMEA_DSC_EXPANSION_INDICATOR:           stringTyp,
	NMEA_DSE_TOTAL_NUMBER:                  intTyp,
	NMEA_DSE_NUMBER:                        intTyp,
	NMEA_DSE_ACK_LEDGEMENT:                 stringTyp,
	NMEA_DSE_MMSI:                          stringTyp,
	NMEA_DTM_LOCAL_DATUM_CODE:              stringTyp,
	NMEA_DTM_LOCAL_DATUM_SUBCODE:           stringTyp,
	NMEA_DTM_LATITUDE_OFFSET_MINUTE:        floatTyp,
	NMEA_DTM_LONGITUDE_OFFSET_MINUTE:       floatTyp,
	NMEA_DTM_ALTITUDE_OFFSET_METERS:        floatTyp,
	NMEA_DTM_DATUM_NAME:                    stringTyp,
	NMEA_EVE_TIME:                          timeTyp,
	NMEA_EVE_TAG_CODE:                      stringTyp,
	NMEA_EVE_MESSAGE:                       stringTyp,
	NMEA_FIR_TYPE:                          stringTyp,
	NMEA_FIR_TIME:                          timeTyp,
	NMEA_FIR_SYSTEM_INDICATOR:              stringTyp,
	NMEA_FIR_DIVISION_INDICATOR1:           stringTyp,
	NMEA_FIR_DIVISION_INDICATOR2:           intTyp,
	NMEA_FIR_FIRE_DETECTOR_NUM_OR_COUNT:    intTyp,
	NMEA_FIR_CONDITION:                     stringTyp,
	NMEA_FIR_ALARAM_ACK_STATE:              stringTyp,
	NMEA_FIR_MESSAGE:                       stringTyp,
	NMEA_GGA_TIME:                          timeTyp,
	NMEA_GGA_LATITUDE:                      floatTyp,
	NMEA_GGA_LONGITUDE:                     floatTyp,
	NMEA_GGA_FIX_QUOLITY:                   stringTyp,
	NMEA_GGA_NUM_SATELLITES:                intTyp,
	NMEA_GGA_HDOP:                          floatTyp,
	NMEA_GGA_ALTITUDE:                      floatTyp,
	NMEA_GGA_SEPARATION:                    floatTyp,
	NMEA_GGA_DGPS_AGE:                      stringTyp,
	NMEA_GGA_DGSP_ID:                       stringTyp,
	NMEA_GLL_LATITUDE:                      floatTyp,
	NMEA_GLL_LONGITUDE:                     floatTyp,
	NMEA_GLL_TIME:                          timeTyp,
	NMEA_GLL_VALIDITY:                      stringTyp,
	NMEA_GLL_FFAMODE:                       stringTyp,
	NMEA_GNS_TIME:                          timeTyp,
	NMEA_GNS_LATITUDE:                      floatTyp,
	NMEA_GNS_LONGITUDE:                     floatTyp,
	NMEA_GNS_ALTITUDE:                      floatTyp,
	NMEA_GNS_MODE:                          stringArrayTyp,
	NMEA_GNS_SVS:                           intTyp,
	NMEA_GNS_HDOP:                          floatTyp,
	NMEA_GNS_SEPARATION:                    floatTyp,
	NMEA_GNS_AGE:                           floatTyp,
	NMEA_GNS_STATION:                       intTyp,
	NMEA_GNS_NAV_STATUS:                    stringTyp,
	NMEA_GSA_MODE:                          stringTyp,
	NMEA_GSA_FIX_TYPE:                      stringTyp,
	NMEA_GSA_SV:                            stringArrayTyp,
	NMEA_GSA_PDOP:                          floatTyp,
	NMEA_GSA_HDOP:                          floatTyp,
	NMEA_GSA_VDOP:                          floatTyp,
	NMEA_GSA_SYSTEM_ID:                     intTyp,
}
